# Generated by Django 5.0 on 2023-12-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_testscore_test_name_alter_testscore_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('testname', models.CharField(max_length=255)),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswers',
            name='user',
        ),
        migrations.DeleteModel(
            name='TestScore',
        ),
        migrations.DeleteModel(
            name='UserAnswers',
        ),
    ]
