# Generated by Django 4.2.2 on 2023-12-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_testresult1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username2', models.CharField(max_length=255)),
                ('testname2', models.CharField(max_length=255)),
                ('result2', models.IntegerField()),
            ],
        ),
    ]
