# Generated by Django 4.2.2 on 2023-12-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_testresult2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username21', models.CharField(max_length=255)),
                ('testname21', models.CharField(max_length=255)),
                ('result21', models.IntegerField()),
            ],
        ),
    ]
