# Generated by Django 4.2.2 on 2023-12-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_testresult21'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username22', models.CharField(max_length=255)),
                ('testname22', models.CharField(max_length=255)),
                ('result22', models.IntegerField()),
            ],
        ),
    ]
